<?php

namespace App\Enums;

enum TaxType: string
{
    case IMPUESTO_RENTA = 'IMPUESTO SOBRE LA RENTA';
    case IMPUESTO_PATRIMONIO = 'IMPUESTO SOBRE EL PATRIMONIO';
    case IMPUESTO_INDUSTRIA = 'IMPUESTO EN INDUSTRIA Y COMERCIO';
    case IMPUESTO_PREDIAL = 'IMPUESTO PREDIAL UNIFICADO';
    case IMPUESTO_IVA = 'IMPUESTO SOBRE LAS VENTAS IVA';
    case IMPUESTO_GANANCIA_OCASIONAL = 'IMPUESTO SOBRE GANANCIA OCASIONAL';
    case IMPUESTO_CONSUMO = 'IMPUESTO NACIONAL AL CONSUMO';
}